import { Heebo, Inter } from "next/font/google";
import "./globals.css";
import Header from "./Header";
import Footer from "./Footer";
import StoreProvider from "./state/StoreProvider";
import { store } from "./state/AuthStore";

const heebo = Heebo({ subsets: ["latin"] });

export const metadata = {
  title: "Apiko Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider store={store}>
      <html lang="en">
        <body className={heebo.className} suppressHydrationWarning={true} >
        <div>
        <Header/>
        {children}
        <Footer/>
        </div>
        {/* <div>
        {auth}
        </div> */}
        </body>
      </html>
    </StoreProvider>
  );
}
